name: Deploy React to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Cài đặt Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      # Bước 3: Cài đặt dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./fe

      # Bước 4: Build dự án React
      - name: Build project
        run: npm run build
        working-directory: ./fe
        env:
          CI: true

      # Bước 5: Đặt biến môi trường (tùy chọn)
      - name: Set environment variables
        run: |
          echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}" >> $GITHUB_ENV
          echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}" >> $GITHUB_ENV

      # Bước 6: Deploy to Vercel (bỏ --scope)
      - name: Deploy to Vercel
        run: npx vercel@25.1.0 --prod --token ${{ secrets.VERCEL_TOKEN }} -m githubCommitSha=$GITHUB_SHA -m githubCommitAuthorName=$GITHUB_ACTOR -m githubDeployment=1 -m githubOrg=namnm309o -m githubRepo=SWD392-FPTU-Lab-Events -m githubCommitMessage="update github action" -m githubCommitRef=main
        working-directory: ./fe