name: Deploy React to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Cài đặt Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      # Bước 3: Cài đặt dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./fe

      # Bước 4: Build dự án React
      - name: Build project
        run: npm run build
        working-directory: ./fe
        env:
          CI: true

      # Bước 5: Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25 # Action chính thức của Vercel
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Token từ Vercel
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # ID của team hoặc tài khoản
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # ID của project
          working-directory: ./fe # Thư mục chứa project
          github-token: ${{ secrets.GITHUB_TOKEN }} # Tùy chọn, để link với GitHub
          scope: namnm309 # Thêm scope là tên team
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}